name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Start API server
      run: npm start &

    - name: Wait for server to start
      run: sleep 5

    - name: Run API tests
      run: ./test.sh

    - name: Stop API server
      run: kill $(lsof -t -i:3000) || true